### ISSUE TITLE
Pattern rename nickname too long

### ISSUE THREAD

**Issue by lflondonol92** [Wolfsblvt/BlossomsPokemonGoManager#168]
I want to rename my pokemons with the name plus ivrating (Bulbasaur_57.78) but the application is giving me an error:
[08/10 09:01:40]: Renaming Bulbasaur failed! Code: ERROR_INVALID_NICKNAME; Nick: Bulbasaur_57.78
What can I do?

**Comment by Wolfsblvt** [comment]
Your chosen nickname is too long. It can only be 12 letters long in the game.

But yes, you are right. We will rework the Error Message, or better: Cut off the name at the end.

**Comment by lflondonol92** [comment]
Can you create an option to make a substring of the name and a round for the iv rating?

**Comment by Wolfsblvt** [comment]
That's possible, yes. And we even thought about that already.

**Comment by nibewiahn** [comment]
When i try to rename the pokemon using %id% is giving a very long ID

testing ID %IV and CP failed because the ID
 [08/10 17:52:01]: Renaming Meowth failed! Code: ERROR_INVALID_NICKNAME; Nick: 6813741741571292521|97.78|430
Than Just the ID
[08/10 17:52:46]: Doing Rename 1 of 1
[08/10 17:52:46]: Renaming Meowth failed! Code: ERROR_INVALID_NICKNAME; Nick: 6813741741571292521

**Comment by nibewiahn** [comment]
Would it also be possible to select the non decimal values to IV rating??? its causing the nickname to be very long i cant event use rating + iv numbers 
Renaming Bulbasaur failed! Code: ERROR_INVALID_NICKNAME; Nick: 57.78|3/13/10

Maybe like %round(ivrating)%

**Comment by nibewiahn** [comment]
[08/10 18:01:04]([Ljava.lang.StackTraceElement;@631356): API Error while renaming Bulbasaur()!

While batch renaming and it stops the renaming

**Comment by Wolfsblvt** [comment]
Thanks for that, will be fixed too

**Comment by nibewiahn** [comment]
awesome job Btw!

**Comment by XargonWan** [comment]
I would suggest to insert the two digits %ivrating%, so instead of 55.78 you get 55 like for example %ivround%.
Then I would insert a trimmed nickname function that gives you the pokemon name minus the character that the software needs to put in the end, like Bulbasa89, could be something like %trimname%.

**Comment by Wolfsblvt** [comment]
Yes, both things are really useful and I will add them while fixing it (:

**Comment by nibewiahn** [comment]
Would it be possible to count the amount of Pokemon we selected?  lets say i selected all my rattatas and i want to know how many are they before I do any action.

**Comment by Wolfsblvt** [comment]
Yes, will be done with the new UI, like written in #24.
At the moment there is a workaround. You can just click on Transfer and there is the number. Then exit.

**Comment by Wolfsblvt** [comment]
Finished the PR, so this should be done here.
