### ISSUE TITLE
Add Moveset to placeholders for Pokémon renaming

### ISSUE THREAD

**Issue by BlasterM2A** [Wolfsblvt/BlossomsPokemonGoManager#185]
First of all, thank the creation of this tool very useful to manage my inventory.
Then I explain my experiment if it is useful for someone (all tested and working for me):

In my case, I renamed the Pokemons with this pattern **Name_Iv_Moveset**, being Moveset a letter that tells me whether it is good to defend (D), attack(A), both (A&D) or none in particular.
I compare Pokemons moves with this web https://rankedboost.com/pokemon-go/venusaur/ (I put Venusaur as example).

To automate this process I decide to add a placeholder to your application:

**1.** I create a function that compares the moveset received with an XML file that has the appropriate movesets of all pokemons (Using the above web as source)

 _¡¡¡¡It's a dirty code, I did it in a short time to test!!!!_

Class that reads the XML and compares -> http://pastebin.com/R07zNSzN
XML file example -> http://pastebin.com/8xMeSxA2

**2.** I add a new Pattern http://pastebin.com/BisRXVxZ

EDIT 1: I round IV to delete decimals and I shortened the name

Result:
![2016-08-11](https://cloud.githubusercontent.com/assets/17768745/17577440/12845aa8-5f7e-11e6-8db8-e099d266ea7b.png)

**Comment by QuadTog** [comment]
I believe the current source for all this info comes from: https://docs.google.com/spreadsheets/d/1Ol33ynE0jBQLF_dyKZYEFDickyyXiTEtQcpYb-ntoH8/

I've even seen new naming schema people are using that lists Offence and Defence from _Duel Ability_ and _Gym Defence_ rounded to 2/3 digits. 
Example: Venusaur - Vine Whip|Solar Beam = A14D4
Example: Venusaur - Razor Leaf|Sludge Bomb = A12D6

Currently my schema is this:
Venusaur - Razor Leaf|Sludge Bomb
A12D6GrPo9AF
Attack = 12 billion, Defence=6 billion, Grass Primary, Poison Secondary, IV is Hex Formatted so 9AF = 9/10/15.

**Comment by Danteleet** [comment]
@QuadTog That is exactly the pattern i'd love to see, more or less. I have my own tool for renaming with IV as hex which i find more practical than decimal values, but renaming with moves is a little trickier.

Having the ability to do this within the tool would be amazing! 
Helps a lot when fighting arenas to chose which pokemon to use, especially lower CP ones for arena powerups when you have to chose between low CP pokemons you have laying around.

**Comment by BlasterM2A** [comment]
Sounds good,
I will try parse that docs to a XML file and add that schema 

I finished my pattern, working fine. I create a XML based on https://rankedboost.com/pokemon-go/ with all pokemons. I create it automatically using Jsoup for read HTML 

Then im going to work to do the new pattern

**Comment by Wolfsblvt** [comment]
I am still confused with most of that really complicated calculations.
I guess that's similar to what #60 wants, right?

I think we will continue with the development of the UI and other features. If someone could write down how to calculate these columns in pseudo-code that is really understandable, and explain why and what, maybe I could take the time to take that on.

We shouldn't rely on third-party sources though. We have the protobuf files and all the data from the APi. So I guess most calculations can be done directly.

**Comment by QuadTog** [comment]
Yeah no probs :) Here's hopefully a better outline or what is required.
Note: Showing Work Tab; View - All Formulae or Ctrl+`.
We've already added IV to Hex so lets ignore that, all we really care about is _Dual Ability_ and _Gym Defence_.

**Dual Ability** (aka Attack) =  Gym Offence (MAX value between NoWeaveMove1 and WeaveDPSMove2) \* Tankiness (Pokemon HP \* Def)

**Gym Defence** (aka Defence) = GymWeaveDPS \* Pkm Atk \* Tankiness (Pokemon HP \* Def)

```
NoWeave = (Move1Power*(1+(Move1STAB*0.25)))*FLOOR(100000/Move1Speed)

WeaveDPS = WeaveCycleDPS*FLOOR(100000/WeaveCycleMS)+(Move1Power*(1+(Move1STAB*0.25)))*FLOOR(MOD(100000,WeaveCycle)/Move1Speed)

WeaveCycleDPS = CEILING(Move2NRG/Move1NRG)*(Move1Power*(1+Move1STAB*0.25))+Move2PWR*(1+Move2STAB*0.25)*(1+(0.5*Move2CRIT/100))

WeaveCycleMS = CEILING(Move2NRG/Move1NRG)*Move1Speed+(Move2Speed+500)

GymWeaveDPS = WeaveCycleDMG*FLOOR(100000/GymWeaveMS)+(Move1Power*(1+(Move1STAB*0.25)))*FLOOR(MOD(100000,GymWeaveMS)/(2000+Move1Speed))

WeaveCycleDMG = CEILING(Move2NRG/Move1NRG)*(Move1Speed+2000)+(Move2Speed+500)
```

**Comment by Wolfsblvt** [comment]
Okay, we got the columns now with PR #213.
Thart means like nearly all of the base of this feature here is done.

What is left is some kind of breakdown of those million-high-numbers into two digits. Guess that would be the best.
If someone has a real good way to do it, just go and tell us. Or submit a PR.

**Comment by xephael** [comment]
@Wolfsblvt 3 numbers would be the most accurate, you can divide the duel ability by 100,000,000 (any more then that and some Pokemon will end up as a 0 and lots of movesets will be considered the same), the Gym offense can be divided by 10,000 (creating a 1 or 2 digit number that is unique most of the time but not always), and you can divide the Gym Defense by 10,000,000 which should create unique numbers for most if not all of the movesets. (this is all done by rounding the number of course, I recommend always rounding up or down to keep the movesets consistently unique from each other, since what really matters is the ranking rather then the actual value.) Basically just removing a bunch of digits from the end of each number.

**Comment by Wolfsblvt** [comment]
Sounds like an idea.
I see what the others come up with, otherwise I will look into it myself.

**Comment by jancr** [comment]
From the screenshot i can see that your (CamiloRguez) trainer level is atleast 36, is that possible w/o botting?

**Comment by jancr** [comment]
QuadTog  where have those formulars been lifted from, particular the "Gym Defence (aka Defence)" because in that one HP defence and attack are evaluated equal, but in the cp formular it is def^0.5 and hp^0.5, if your formulars are correct then cp is a terrible proxy for actual combat power!, and all pokemons with low attack should be used when attacking friendly gyms as they would be very strong "for their combat power"... 

my (naive) assumption was simply 

```
damage = scaling_factor * WeaveCycleDPS * attack^2
damage_needed_to_kill = hp * defence
```

or something similiar, that would result in 2 pokemons with the same combat power and the same moves would perform equal.

a pokemon with 100/50/50 and one with 50/100/100 will have the same combat power, but the way I understand your formular the one with 50/100/100 will be twice as strong?!?!

**Comment by xephael** [comment]
@jancr Keep in mind that Gym defense is totally different from attacking the gym. HP and defense matter more on a defending Pokemon because defending Pokemon do not attack in the same way an attacking Pokemon would. Some moves are better at defending then they are at attacking.

**Comment by btracz** [comment]
Perhaps exotic unicode chars can make it more human readable (enclosed alphanumerics to replace hexa, with black background over 10). We can also reduce length by using symbols for types such as Ψ (Psychic) or ☣ (Poison)... leaving space for another info.
PoGo app seems to support it pretty well :
[![unicode-chars.png](https://s10.postimg.org/7b67ihudl/unicode_chars.png)](https://postimg.org/image/tzvei2br9/)

However, Blossom's interface can't render all unicode chars replacing it by a square... maybe a font issue.

**Comment by Wolfsblvt** [comment]
Could be something that would work, yes.
Have to think about it. Maybe it's an idea. You could even make it optional to use that.

**Comment by Ljaysoft** [comment]
I'll test in the GUI I'm currently making, but I really like the idea

**Comment by Ljaysoft** [comment]
@btracz what does the black background mean? (or is it just for example)

**Comment by Ljaysoft** [comment]
Apparently, the Labels in javafx supports unicode, just type \uXXXX with the Xs the hex code inside a string

**Comment by xephael** [comment]
That's a really good idea

**Comment by Wolfsblvt** [comment]
So, I would say we make it an option in the future. Wouldn't force the user to have those funny little icons.

**Comment by btracz** [comment]
A keyboard inside the renaming popup with those chars would be nice and could serve as a caption.

**Comment by xephael** [comment]
@btracz They need to be used in the placeholders, to do it manually you could just paste them in from somewhere

**Comment by jancr** [comment]
@torin555 as fare as I understand the difference between gym defense and attack is that the attacking pokemon attacks 2 seconds slower, this means that slow moves are better for defense, but I fail to see how that makes the attack stat less valuable, if a pokemon attacks half as often, then cutting its damage in half (via lower attack) or cutting its life in half (via half stamina) should yield the same result... can you please explain why attack is best for attackers as that does not make sense to me, and can you confirm that it scales linear as the formulars suggest?

**Comment by jancr** [comment]
@btracz that is an amazing idear

**Comment by Wolfsblvt** [comment]
Added the first iteration of placeholder patterns with PR #239.
It's those calculated values of the new formulas as a percentage based on the highest possible value of all Pokémon. Currently with two characters. Seems okay. More utility will be added later then.

**Comment by pccck** [comment]
I finished a feature for my own branch that renames pokemon with a pattern mostly copied from https://www.reddit.com/r/TheSilphRoad/comments/4x5czg/ultimate_pokemon_naming_system/ , although instead of utilizing the "duel ability" score for attack and defense, my code fetches the attack and defense scores from http://www.pogomoves.com/defense/gym-defense.php & http://www.pogomoves.com/offense/gym-offense.php.

The resulting name could be DD78 A100D62 for a dragonite with 78% cp and a moveset of Dragon breath & dragon claw. For me this naming pattern feels the most intuitive and informative to quickly assess gym effectiveness of Pokémon.

If you're interested, I could clean up the code a bit and submit a pull request.

**Comment by Wolfsblvt** [comment]
You should really meet up with @QuadTog and @607ch00 on our Discord channel.
I even created a channel for that math-talk there. Guess we shouldn't use like dozens of different calculations, but find a way to get the few best ones.

I will close here now. More stuff about what we change there should be discussed on Discord then.
The features in it's base do exist now.
