### ISSUE TITLE
Copying of Duel Ability, Gym Offense, Gym Defense values into Excel displays long list of numbers

### ISSUE THREAD

**Issue by a95patel** [Wolfsblvt/BlossomsPokemonGoManager#317]
I did not see an issue open for this. After the update, I copied the new data into excel and for the Duel Ability, Gym Offense, Gym Defense columns I saw a long string of numbers. 

In the program I see 11 for Duel Ability but when I copy the data into excel the value that is being copied is 2318662656. This is happening for the other 2 columns too. Also another pokemon with a Duel Ability of 11 does not have the same value when copied over to excel. For the second pokemon the value in excel is 2351088300.

Earlier today, I had thought that the value was stored as a decimal and we were just seeing the whole number in the program. And that when copying the values to excel, the whole number was not being copied over. But now that I am looking at it again, I was wrong. 

Hopefully this can be fixed for the next update. 

Thanks,
Aatika

**Comment by Wolfsblvt** [comment]
Okidoki, I understand the issue.
The point is: Those three column values are actually those really high numbers. That's the original value for Duel Ability, Gym Offense and Gym Defense.
But we decided to shorten it to make it more understandable for the user, and so that it can be added to the renaming patterns with only two characters.
So what really happens is that the high number gets compared to the highest possible number atm (which is Mewtu), so the percentage of that is being displayed.
If you hover over the column you can even see the real number in the tooltip.

Yes, it is a bug that when copying it over to excel that the real number is chosen. But I guess that have to wait for issue #63 to be implemented.
