### ISSUE TITLE
In Advanced IV Calculation, Chansey with 15/15/14 get calculated as 100% IV

### ISSUE THREAD

**Issue by bengine** [Wolfsblvt/BlossomsPokemonGoManager#385]
Using Advanced IV Calculation somehow calculated Lv. 1 Chansey with 15/15/14 IV to be 100%. 

![chansey](https://cloud.githubusercontent.com/assets/22230273/18574623/5f2084a0-7c01-11e6-9769-36e5566fae39.JPG)

**Comment by Wolfsblvt** [comment]
Guess that's due to rounding. Chansey is an interesting example, because of her insanely high Stamina, and then quite low Attack and Defense.
Stamina:    500
Attack: 40
Defense:    60

Now Guess how much difference 1 stamina does when she already has 514? That's the math, that's why that advanced calculation even exists :P
You can even calculate it yourself.

The point is... is this really a bug then?
