### ISSUE TITLE
time between Evloves

### ISSUE THREAD

**Issue by DrDragonKiller** [Wolfsblvt/BlossomsPokemonGoManager#412]
In the _config file_ I saw that:
"evolve": {
            "min": 3000,
            "max": 12000
        }

means you wait between 3 and 12 seconds between evolves =>150 -600 evolves
**Is that save?** Because normally you would have to wait like 25 seconds =>around 72 evolves

And will it work when I turn on a lucky egg than close the app and open this tool and evolve all pokemon (with specific name or with favorite)?

And will there be a lucky egg evolve option and calculator in the next release?

**Comment by Wolfsblvt** [comment]
Yes, it means exactly that. If it is safe? Decide for yourself.
I myself have used this at least a dozen times and am still here, not banned :P

Yes, this will work. It is even the intended way to do this with this tool.  You don't even have to close your smartphone app. I would keep it open to mask your activity better.

In the next release? Guess not. But in the future yes. That's something planned.

**Comment by DrDragonKiller** [comment]
thank you :+1:

**Comment by adr-sit** [comment]
"evolve": {
"min": 3000,
"max": 12000
}
Is the min / max  the time wait between 2 evolutions (1 after the other) , or the time wait to submit a evolution request (which may result in 2 or more evolutions progressing simultaneously)? 

Can I change the values?

**Comment by Wolfsblvt** [comment]
It's the time to wait between two evolution requests. It really waits until the server returns a result (which is far before the animation ends of course, that's why we have a delay).
The tool can't really tell when the animation on your phone would have finished. I mean it could, if you set the delays higher, for example.

Sure you can. Just edit the values in the config file, then refresh the tool or restart it. The delay times are in milliseconds.

**Comment by Wolfsblvt** [comment]
Answered in #478.
