### ISSUE TITLE
Anyone still using this program?

### ISSUE THREAD

**Issue by adr-sit** [Wolfsblvt/BlossomsPokemonGoManager#470]
Any softban / perm ban yet

**Comment by Wolfsblvt** [comment]
Sure, many people using this tool (:

And no, I haven't heard of any soft or permanent ban yet.
There was one user who posted a screenshot of that "use of 3rd-party app"-warning and said he only used BPGM, but that's one out of... hundreds of active users.

Sure, know the risks (Niantic **can** likely detect you, cause of old API calls and stuff), but on top of that the tool should be fine.

**Comment by billyyao** [comment]
so the old APIs still available for use? I noticed most of the sniping sites unable to provide coordinates due to API updates. Wondering why this manager is not affected.

Are we facing an increased chance of flagged by Niantic after the API update? Or it is the same risk as before?

Really appreciate your work on this tool :)

**Comment by Wolfsblvt** [comment]
Yes, it is. The API endpoint is the same, it hasn't changed since the beginning. What has changed are that some calls were removed and other required some kind of _encrypted token_ to verify that you are the app.
That calls that requires a new token now are "blocked". And by blocked it just means that they return null/empty responses, not that they do not work.
BPGM uses calls that weren't affected by the new security system. That means everything still works fine.

I don't think the chance of getting flagged is increased to weeks before. It's really the same. So know the risks, otherwise it works.

**Comment by plebicidal** [comment]
Looks like update from last 24hrs finally took out the api this was using.. :(
RIP pogomanager

**Comment by Wolfsblvt** [comment]
I don't think so.
The server were down for hours right now.
