### ISSUE TITLE
Evolve speed

### ISSUE THREAD

**Issue by adr-sit** [Wolfsblvt/BlossomsPokemonGoManager#478]
I read this post and have 1 question.

https://github.com/Wolfsblvt/BlossomsPokemonGoManager/issues/412

"evolve": {
"min": 3000,
"max": 12000
}
Is the min / max the time wait between 2 evolutions (1 after the other) , or the time wait to submit a evolution request (which may result in 2 or more evolutions progressing simultaneously)?

Can I change the values?

**Comment by Wolfsblvt** [comment]
It's the time to wait between two evolution requests. It really waits until the server returns a result (which is far before the animation ends of course, that's why we have a delay).
The tool can't really tell when the animation on your phone would have finished. I mean it could, if you set the delays higher, for example.

Sure you can. Just edit the values in the config file, then refresh the tool or restart it. The delay times are in milliseconds.
