### ISSUE TITLE
Dps don't match pokemongodb

### ISSUE THREAD

**Issue by spiv0024** [Wolfsblvt/BlossomsPokemonGoManager#480]
First of all thank you for doing this. Great App!. However, I noticed that dps is not consistent with pokemongodb.com. Which numbers should we trust? Is pokemongodb more reliable? One example is Dragonite, none of your Move 2 dsp match the dps on pokemongodb.com. Also, does your dps includes STAB? Looks like it does for Dragonite's Dragon Breath.

**Comment by Wolfsblvt** [comment]
I'll quote Discord here.

### Question by @smintario

> In the calculations for the moves, is STAB always in calculations? Tentacruel gives 22.44 dps for sludge waves in BPGM for example, while it's listed with 25.7 on silph road (stab considered). If stab is not considered, why is it like that?

### Answer by @QuadTog

> Sludge Wave:
> CD         EPU     DPS        DPS w/STAB     'True DPS'     BPGM DPS
> 3.40      -100    20.59     25.74                    22.06             22.44
> 
> 'True DPS' includes Tentacruel's Base Attack Stat.
> BPGM includes Tentacruel's Base Attack Stat AND your Pokemon's unique Attack IVs into the calculation.
> 
> Hope that helps :smiley:

So the difference should be coming from that we are including IVs as well, a list surely doesn't.
Does that answer your question?

**Comment by spiv0024** [comment]
OK I thought of that too but it still doesn't add up. I have two Dragonites both 100% IV, one with Dragon Claw and another one with Hyper Beam. BPGM shows dps of 21.88 and 21.82 respectively. However, on pokemongodb these dps' are 27.3 and 24.0 (much larger difference). Also, how come BPGM doesn't adjust move 1 dps. My 100% Dragonites have Dragon Breath and Steel Wing, and BPGM dps' exactly match pokemongodb, 15 and 11.3.

**Comment by Wolfsblvt** [comment]
I am not sure, but also don't have the time to dig into very deep.
We surely include Stab though.

The dps calculation can be found here: https://github.com/Wolfsblvt/BlossomsPokemonGoManager/blob/develop/src/me/corriekay/pokegoutil/utils/pokemon/PokemonCalculationUtils.java#L78-L94

**Comment by QuadTog** [comment]
Just a quickie mate, are we are talking about the Move DPS displayed in the 'Move 1' and 'Move 2' columns (not the back-end functions)?

 If so that's because we're using the Base IV's and not the Pokemon's bonus IV's for type calculations. Move 1 DPS doesn't adjust because we don't include a Charge-Delay in Milliseconds for Quick Attacks nor do we currently including dodge damage reduction.

Actually we could probably improve that further:

Damage = Floor ( .5 Attack / Defense \* Power \* STAB \* Effectiveness ) + 1

Where Attack and Defense are defined as:
Attack=(BaseAttack+AttackIV)
Defense=(BaseDefense+DefenseIV)

Reference: https://www.reddit.com/r/TheSilphRoad/comments/4wzll7/testing_gym_combat_misconceptions/?st=iurkbzuw&sh=040f9d6f
