### ISSUE TITLE
Three suggestion for future things: Labeling system, Sprites/Images of Pokémon

### ISSUE THREAD

**Issue by Scott7789** [Wolfsblvt/BlossomsPokemonGoManager#49]
I want to preface by saying, I'm not a developer: just a very active user. Many of these bugs and suggestions may have probably already been pointed out, but I want to help the project in any way a layman, such as myself, can. Here's what I've noticed in extensively using the 0.1.1 release:

Bugs:

-After a batch has been transfered/evolved/etc the sorting conventions reset, along with the order in which you had arranged the columns.
-Nidoran Male/Female Symbols look different than intended.

Suggestions: (The more pressing ones are first. Minor ones last.)

-Ability to Rename Individual Pokémon within the client.
-Labeling or Checkbox System. To label Pokémon "To Evolve Later" or "To Transfer Later." Perhaps some sort of simple hotkey for quick marking as you go down the list.
-Ability to toggle Favorite/Unfavorite Pokémon.
-Ability to color code a horizontal row to organize identify a Pokémon of personal significance.
-Option to show Sprites for each pokemon. It's minor, but it helps me distinguish between many rows of "Nidoran" and "Exeggute/Exeggutor," that look similar when you glance quickly at blocks of text.

Ex:
Exeggute
Exeggute
Exeggute
Exeggute
Exeggutor
Exeggute
Exeggute

-Column to sort by how long you've owned said Pokémon. Similar to the "Recent" Pokémon screen within the app.
-Column to sort by a Pokémon's "Maximum Potential CP" if it were to reach level 40.

None of these are glaring needs; just all things that I feel can help the program reach its full potential. Thank you all for your hard work and dedication. Love the product.

**Comment by Wolfsblvt** [comment]
Bug's are both known, yes. Suggestions are quite good, some of them even something I didn't had in mind already.
Guess we will talk what we will implement and create individual enhancement issues for that.

Thank you for posting your thoughts.

**Comment by Wolfsblvt** [comment]
I'll go through your list and answer detailed, so that I do not forget anything.
- **After a batch has been transfered/evolved/etc the sorting conventions reset, along with the order in which you had arranged the columns.**  
  Sorting bug is here #43, while saving or column order is here #65 now.
- **Nidoran Male/Female Symbols look different than intended.**  
  Encoding and stuff is here #46.
- **Ability to Rename Individual Pokémon within the client.**  
  Renaming will be possible with #47, individual too.
- **Ability to toggle Favorite/Unfavorite Pokémon.**  
  Handling favorites is this issue: #58
- **Column to sort by how long you've owned said Pokémon. Similar to the "Recent" Pokémon screen within the app.**  
  Was added already now with PR #54
- **Column to sort by a Pokémon's "Maximum Potential CP" if it were to reach level 40.**  
  Added that with PR #54 too :P

So what's left are those points. Guess @Blossomforth should decide which of those should be added.  
I'll keep that issue open in that time.
- [ ] Labeling or Checkbox System. To label Pokémon "To Evolve Later" or "To Transfer Later." Perhaps some sort of simple hotkey for quick marking as you go down the list.
- [ ] Ability to color code a horizontal row to organize identify a Pokémon of personal significance.
- [ ] Option to show Sprites for each pokemon. It's minor, but it helps me distinguish between many rows of "Nidoran" and "Exeggute/Exeggutor," that look similar when you glance quickly at blocks of text.

**Comment by ghost** [comment]
THe remaining 3 suggestions are all obviously things we'd be happy to have in the tool, but currently we do not have any specific milestone to attach them to. I'll keep the issue opened here, and once we dont have any other important things to do (such as fixing bugs and the like) I'm sure someone will want to pick up these changes and implement them.

**Comment by Wolfsblvt** [comment]
Sprites has it's own issue now: #268.
The other two will be considered with the new UI. Will close here now then.
