### ISSUE TITLE
ERROR OVER_QUERY_LIMIT

### ISSUE THREAD

**Issue by poiuytrezaur** [Wolfsblvt/BlossomsPokemonGoManager#493]
After loading my pokemon list I had this error displayed in the pokemon list on several pokemons : caught city/caught locations : ERROR OVER_QUERY_LIMIT

**Comment by Wolfsblvt** [comment]
Yes. That's caused by the Google Maps API, and sadly nowhere explained in BPGM :-/

I can explain it in short here. For Pokémon, the Pokemon server just returns a so-called cellId where it was caught. From that, you can calculate the geo-coordinates, which are shown in a column too.

But to get the location itself, as a text, we need to get it somewhere. For that, there exists the Google Geocode API as part of the Google Maps API. What BPGM does is send a coordinate to Google Maps and asks how the location is called, then it extracts the answer and caches it in a local `locations.json` file.
The Google API only accepts 50 requests per second though ([source](https://developers.google.com/maps/documentation/geocoding/usage-limits), to limit API overload. So if you have more than 50 different locations for your Pokémon, BPGM can only display the first 50 and displays `OVER_QUERY_LIMIT` for the rest.

If you refresh the list, the next bunch of 50 locations should be queried. Until you have all ready.

**Comment by poiuytrezaur** [comment]
Ok thanks !
