### ISSUE TITLE
Suggestions on things you could add

### ISSUE THREAD

**Issue by Froodle** [Wolfsblvt/BlossomsPokemonGoManager#516]
Hey, First of all thankyou for making this application and i love it, however me and my friends who also use the app have a few  suggestions you could add.
-Option to have a Delete all if cp < ??? and iv < ???% and evolvable = 0 or null  also  (keep strongest unique pokemon tickbox?) with values changeable by the user 
-Mass rename Pokemon with their IV levels
-For very ban conscious people have an option to increase the random delay between actions
-Add and remove columns with multiple tickboxes with a "view" context menu in the menu bar 

Thankyou again :D

**Comment by kribjo** [comment]
Just some help/info for the issue poster.

> -Mass rename Pokemon with their IV levels

Already implemented. Select those you want to rename, click Rename, enter %-pattern for whatever IV display format you wish, click OK.

> -For very ban conscious people have an option to increase the random delay between actions

Already implemented. Edit min and max delay settings per action in config.json file

**Comment by Froodle** [comment]
Thank you very much I never noticed this,  good job on the developers for implementing this and sorry for wasting your time

**Comment by Wolfsblvt** [comment]
You don't waste my time :P
Suggestions are always good to hear, and if many poeple are asking for a feature that is already implemented, then it's maybe too... hidden, and I could improve it.
So feel free to make suggestions.

I would prefer single issues for every suggestion though, grouped issues just lead to me missing something or other people can't see that something was already suggested, etc.

For the two open options: Customizable columns with saving order and size, make them hideable etc is already planned.  
The first thing sounds really difficult, and looks very user-specific. Isn't the advanced list and this tool not the reason so that you can quickly do that manually and decide what you want to keep and what not?

**Comment by Froodle** [comment]
It certainly can be achieved by your application and I love it for that,  it was simply a quicker method of doing it,  me and my friends all seem to use it for clearly inventory of none perfect iv and low cp pokemon.  I supply thought having a one click button to do this would be appreciated by some,  I can however understand it would be a minority and therefore shouldn't be coded so it's fine.  :D thanks again
