### ISSUE TITLE
Power up, over the allowed

### ISSUE THREAD

**Issue by hajnalmt** [Wolfsblvt/BlossomsPokemonGoManager#533]
Firstly, thank you for the app, I use it a lot. 

In BPGM you can power up your Pokemon to a higher level, then you can in the game itself. For example if you are at level 20 you can power up in the game until level 21,5. But in BPGM you can power it up to any level you want. It can be risky, because if you have a higher level pokemon, then you allowed to it's obvious, that you are cheating, if somebody reports you. Maybe there should be a warning for that. (I'm not sure about it, sy should test it, but I think you can power up your pokemon above the most achievable in game also, so for example now the max cp to reach in the game is dragonite with lvl 39, 3530cp but with BPGM you can power up to lvl 40 reaching 3581 cp, I'm not enough leveled to test it out)

**Comment by Blup008** [comment]
When I tried to power up a pokemon, I got this message:
**[19:15:11]: Skipping power-up of Vaporeon. It is already MaxCP: 2928**
But with the 'two finger' powerup (https://www.reddit.com/r/TheSilphRoad/comments/5ont44/double_powerup_to_exceed_the_level_cap_and_save/), it is possible to train your pokemon to trainer level +2. My Vaporeon is 35.5 and I am level 34. So the tool should make it able to powerup to 36. And not give me the error that I'm already at max CP, because the server allows me one more powerup.

**Comment by Wolfsblvt** [comment]
Is this really still an issue? I have implemented max level powerup some time ago.
