### ISSUE TITLE
Bug: Add check for existing saved credentials

### ISSUE THREAD

**Issue by weblue** [Wolfsblvt/BlossomsPokemonGoManager#6]
If the credentials already exist, there's no reason to have the popup come again for saving. Automatically logging in based on saved credentials might also be a decent feature given that a logout function is added for players with multiple accounts.

**Comment by SuigetsuSake** [comment]
Until there is a logout feature things must stay this way otherwise we couldn't switch google account x) i was afraid to have to redownload app but saying no to the popup erase the old setting and thus i was able to reconnect with a different google account.

Anyway I still agree that login/logout needs improvement

**Comment by Ljaysoft** [comment]
I'm gonna implement a better way of handling the login, if @Blossomforth wants to work on other stuff first.

**Comment by weblue** [comment]
I'm gonna try to do lucky egg support when I get home in an hour or so.

**Comment by ghost** [comment]
@Ljaysoft: Whats your idea? I was about to work on this one, but if you want to handle it, that'd be fine. :)

**Comment by Ljaysoft** [comment]
Well, since you're working on it I'll do something else, but I would:
-add a checkbox on the first login screen for automatic login
-add a logout button in the menu(which reopens the login window
-clean up the useless checkboxes if login is done automatically with saved credentials (and not asking to save credentials again, unless there are no saved credentials
-adding a multi-account support for switching from one account to the other that are saved

**Comment by weblue** [comment]
Saw the pull
