### ISSUE TITLE
Make option to exclude families from search

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/BlossomsPokemonGoManager#62]
When searching for Pidgey, it shows every Pokémon of that family, cause of the multi-search-bar. Sometimes that's not wished behavior.

We should add a settings toggle that can deactivate including of families from search. This toggle should be in the settings Window, so depends on #61.

Originally suggested in #56. Pinging @ISeeTanamon and @phronx.

**Comment by ghost** [comment]
Has anyone had any use out of the family search? If its not really that great of a feature, might as well just chuck it. I figured it was an interesting idea to have, but it seems like it might be better off removed.

**Comment by Wolfsblvt** [comment]
Dunno. I don't.
Would be another solution, yeah. Maybe display for each Pokémon in a column what the highest family evolution is? In that case you can order after that. Should be enough.
And columns are hidable soon.

**Comment by phronx** [comment]
I do make use of the family search to see what my highest IV pokémon is in the family. Might be an idea to be able to search for multiple pokémon the same time? Pidget;Pidgeotto;Pidgeot would result in the same as searching for Pidgey now.

**Comment by ISeeTanamon** [comment]
The search feature is for sorting multiple pokemon in one single view. Imagine if I had say... 15 Pikachus around the same CP ingame, and wanted to only transfer using @Blossomforth 's app because I can see my IV's. I'd go to Pikachu as a search term, and then sort by CP within the Pikachu search view. 

Not sure why searching "Pidgey" brings up "Pidgeotto' too if I'm using 'pidgey'. Thats what my original defect was about.

**Comment by Wolfsblvt** [comment]
I have explained that already. It's cause they are all part of the Pidgey family. That's what this issue is about :D

**Comment by Wolfsblvt** [comment]
Guess from that issue we have two plans:
- [ ] Make option to exclude Family search from that bar
- [x] Multi-Sort, separated with semicolons

**Comment by Wolfsblvt** [comment]
Is included in the PR #245.
