### ISSUE TITLE
Bug: Favorites need to be handled so they can't be transferred

### ISSUE THREAD

**Issue by weblue** [Wolfsblvt/BlossomsPokemonGoManager#8]
Favorite support might also be good to have.

**Comment by ghost** [comment]
This was implemented with one of the pull requests that I woke up to this morning. However, it merely restricts the user from ever tranferring a favorite pokemon. I'm assuming what would need to happen, is they'd need to unflag it as a favorite, refresh the list of pokemon, and then transfer it.

For now, i think thats fine, but if you think further handling of the issue is required, let me know!
